version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files in .github/workflows will be checked
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
